export const WALLET_LIQUALITY = 'WALLET_LIQUALITY';
export const WALLET_METAMASK = 'WALLET_METAMASK';

// actions
export const SESSION_CONNECT_WEB3 = 'SESSION_CONNECT_WEB3';
export const CONTRACT_GET_UNITROLLER_ADDRESS = 'CONTRACT_GET_UNITROLLER_ADDRESS';

// mutations
export const SESSION_SET_PROPERTY = 'SESSION_SET_PROPERTY';
export const CONTRACT_SET_PROPERTY = 'CONTRACT_SET_PROPERTY';

// getters
export const SESSION_GET_WALLET_NAME = 'SESSION_GET_WALLET_NAME';
