export const WALLET_LIQUALITY = 'WALLET_LIQUALITY';
export const WALLET_METAMASK = 'WALLET_METAMASK';
export const WALLET_CONNECT = 'WALLET_CONNECT';

export const USER_ACTION_MINT = 'USER_ACTION_MINT';
export const USER_ACTION_BORROW = 'USER_ACTION_BORROW';
export const USER_ACTION_REDEEM = 'USER_ACTION_REDEEM';
export const USER_ACTION_REPAY = 'USER_ACTION_REPAY';

export const RBTC_SYMBOL = 'tRBTC';
export const CRBTC_SYMBOL = 'cRBTC';

export const ROUTE_NAMES = {
  BALANCE: 'Balance',
  SAVINGS: 'Supply',
  DEBTS: 'Borrow',
  TUTORIALS: 'Tutorials',
  OVERVIEW: 'Overview',
};

// actions
export const SESSION_CONNECT_WEB3 = 'SESSION_CONNECT_WEB3';
export const SESSION_DISCONNECT_WALLET = 'SESSION_DISCONNECT_WALLET';
export const SESSION_GET_CHAIN_ID = 'SESSION_GET_CHAIN_ID';

// mutations
export const SESSION_SET_PROPERTY = 'SESSION_SET_PROPERTY';

// getters
export const SESSION_GET_WALLET_NAME = 'SESSION_GET_WALLET_NAME';
export const SESSION_IS_CONNECTED = 'SESSION_IS_CONNECTED';
